In [8]:
from train import * # Train network: takes long

In [9]:
testing_generator.indeces = np.arange(len(testing_generator.path_names))

In [11]:
true = np.array([([1, 0] if path[0] == 'c' else [0, 1]) for path in testing_generator.path_names])

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]])

In [12]:
from keras.models import load_model
model = load_model("model")

In [20]:
pred = model.predict(testing_generator[2][0])
pred

array([[4.3605915e-03, 9.9563944e-01],
       [2.9128692e-03, 9.9708718e-01],
       [2.3416914e-03, 9.9765825e-01],
       [5.2670093e-04, 9.9947327e-01],
       [1.1550231e-02, 9.8844969e-01],
       [3.0358168e-03, 9.9696416e-01],
       [3.9243107e-04, 9.9960762e-01],
       [3.3356677e-04, 9.9966645e-01],
       [1.2008214e-03, 9.9879920e-01],
       [1.8149404e-03, 9.9818498e-01],
       [1.7227074e-03, 9.9827731e-01],
       [7.2878879e-01, 2.7121121e-01],
       [5.1908783e-04, 9.9948090e-01],
       [2.4817948e-04, 9.9975187e-01],
       [2.1380722e-04, 9.9978620e-01],
       [6.0815562e-04, 9.9939179e-01],
       [9.2012860e-04, 9.9907982e-01],
       [3.2019389e-09, 1.0000000e+00],
       [2.2087934e-04, 9.9977916e-01],
       [4.3012798e-04, 9.9956983e-01],
       [1.2278963e-04, 9.9987721e-01],
       [7.7405875e-03, 9.9225944e-01],
       [2.0300585e-03, 9.9796993e-01],
       [2.5678915e-04, 9.9974316e-01],
       [4.9778624e-05, 9.9995017e-01],
       [2.7027758e-04, 9.

ValueError: Found input variables with inconsistent numbers of samples: [146, 128]

In [21]:
list(testing_generator[2][1])

[array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1])]