In [1]:
from train import *

Using TensorFlow backend.


In [2]:
testing_generator.indeces = np.arange(len(testing_generator.path_names))

In [3]:
from keras.models import load_model
model = load_model("model")

In [12]:
pred = model.predict(testing_generator[6][0])
pred

array([[2.8840921e-04, 9.9971157e-01],
       [6.9079781e-03, 9.9309206e-01],
       [3.5197693e-03, 9.9648029e-01],
       [2.6360394e-03, 9.9736398e-01],
       [2.7664384e-04, 9.9972337e-01],
       [1.7097904e-04, 9.9982893e-01],
       [1.4903717e-04, 9.9985099e-01],
       [4.3659465e-04, 9.9956340e-01],
       [7.0250835e-06, 9.9999297e-01],
       [3.5351487e-03, 9.9646485e-01],
       [2.3800577e-03, 9.9761993e-01],
       [5.9260631e-01, 4.0739372e-01],
       [1.8644581e-02, 9.8135537e-01],
       [5.5478383e-03, 9.9445218e-01],
       [2.7827121e-04, 9.9972171e-01],
       [4.0469595e-04, 9.9959534e-01],
       [7.2844610e-05, 9.9992716e-01],
       [1.3802259e-03, 9.9861979e-01],
       [2.7405225e-02, 9.7259480e-01],
       [1.2940395e-04, 9.9987054e-01],
       [6.6592568e-04, 9.9933404e-01],
       [4.5626624e-03, 9.9543732e-01],
       [3.6217335e-03, 9.9637824e-01],
       [2.7591779e-03, 9.9724078e-01],
       [1.5450768e-04, 9.9984550e-01],
       [4.3766382e-03, 9.

In [11]:
list(testing_generator[6][1])

[array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1])]